### ISSUE TITLE
Building virtual environment

### ISSUE THREAD

**Issue by HappyDay-design** [romainducrocq/DQN-ITSCwPD#1]
Thank you very much for your coding.

I followed your instructions 
-make: `cd bin/ && bash make.sh`
![image](https://user-images.githubusercontent.com/82990411/185162472-293a1654-c35d-4ad6-9d83-789ac4210f10.png)

 and run 
`bash train.sh` or `bash observe.sh` but it had errors
FileNotFoundError: [Errno 2] No such file or directory: './venv/sumo/bin/sumo'

I would like to ask you how to run the model without a virtual environment and building sumo. Because I install sumo by `sudo apt-get install sumo sumo-tools sumo-doc`
And could I use a conda environment instead of a virtual environment?

**Comment by romainducrocq** [comment]
Install as root, with: sudo bash make.sh.
I don't use conda if not specifically needed, this project was designed for venv.

**Comment by HappyDay-design** [comment]
Thank you very much. I can run your models
